refactor(setup): improvements when installing Ansible with Homebrew
2020-09-06:

- Upgrade outdated Ansible Homebrew formula
- Detect installed Ansible Homebrew path correctly during install

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -3,6 +3,10 @@
 # Setup script for https://github.com/markosamuli/linux-machine and
 # https://github.com/markosamuli/macos-machine Ansible playbooks.
 #
+# 2020-09-06:
+# - Upgrade outdated Ansible Homebrew formula
+# - Detect installed Ansible Homebrew path correctly during install
+#
 # 2020-09-04:
 # - Re-install Xcode Command Line Tools (CLT) after upgrade
 # - Wait for Xcode CLT installation to complete in the background
@@ -69,6 +73,7 @@ install_ansible=1     # Install Ansible
 install_roles_force=0 # Force overwriting existing Ansible roles
 update_roles=0        # Update Ansible roles to the latest versions
 print_versions=0      # Print Python and Ansible versions
+upgrade_ansible=0     # Upgrade Ansible to the latest version
 
 # System properties
 is_macos=""        # macOS
@@ -166,6 +171,9 @@ show_help() {
   --no-install-roles
       Disable Ansible roles from being installed or updated
 
+  --upgrade-ansible
+      Upgrade outdated Ansible version (macOS with Homebrew only)
+
   --verbose
       Enable verbose Ansible output
 
@@ -246,6 +254,9 @@ install_macos_dependencies() {
     if is_true "${install_ansible}"; then
         install_ansible
     fi
+    if is_true "${upgrade_ansible}"; then
+        upgrade_ansible
+    fi
 }
 
 # Install Xcode Command Line Tools
@@ -293,6 +304,37 @@ install_ansible() {
     fi
 }
 
+# Upgrade existing Ansible installation to the latest version
+upgrade_ansible() {
+    if is_true "${is_macos}"; then
+        upgrade_ansible_on_macos
+    elif is_true "${is_linux}"; then
+        error "upgrading Ansible on Linux is not supported"
+    else
+        error "Your system is not supported"
+        exit 1
+    fi
+}
+
+# Is the installed Ansible version outdated
+is_ansible_outdated() {
+    if ! is_ansible_installed; then
+        debug "ansible not installed, not marking it as outdated"
+        return 1
+    fi
+    # Check Homebrew installation
+    if is_ansible_homebrew_enabled; then
+        local outdated
+        outdated=$(brew outdated -q ansible)
+        if [ -n "${outdated}" ]; then
+            debug "outdated Ansible Homebrew formula found"
+            return 0
+        fi
+    fi
+    # Not supporting Linux or PyPI version checking
+    return 1
+}
+
 # Is Ansible installed on the PATH or in the custom location
 is_ansible_installed() {
     # Check Homebrew installation
@@ -302,6 +344,7 @@ is_ansible_installed() {
             debug "brew --prefix ansible is empty"
             return 1
         fi
+        debug "ansible Homebrew formula found"
     fi
     # Fail if 'ansible --version' doesn't work
     local version
@@ -364,27 +407,74 @@ install_ansible_on_linux() {
     exit 1
 }
 
+# Upgrade exisging Ansible installation on macOS
+upgrade_ansible_on_macos() {
+    debug "upgrade Ansible on macOS"
+
+    configure_ansible_on_macos
+
+    if ! is_ansible_outdated; then
+        debug "outdated Ansible version not detected"
+        return 0
+    fi
+
+    if is_ansible_pypi_enabled; then
+        error "upgrading Ansible PyPI packages is not supported"
+        return 1
+    fi
+    if ! is_ansible_homebrew_enabled; then
+        error "upgrading Ansible on macOS requires Homebrew"
+        return 1
+    fi
+    if ! upgrade_ansible_with_homebrew; then
+        error "failed to upgrade Ansible"
+        return 1
+    fi
+}
+
+# Upgrade Ansible installed with Homebrew
+upgrade_ansible_with_homebrew() {
+    echo "*** Upgrading Ansible with Homebrew..."
+    brew upgrade ansible ||
+        {
+            error "Failed to upgrade Ansible with Homebrew"
+            exit 1
+        }
+}
+
+# Configure Ansible on macOS
+configure_ansible_on_macos() {
+    debug "configure Ansible on macOS"
+    # Enable Homebrew installation as the default option if neither Homebrew or
+    # PyPI installation option have been set or if PyPI has been disabled.
+    if [ -z "${ansible_homebrew_enabled}" ]; then
+        if [ -z "${ansible_pypi_enabled}" ]; then
+            debug "PyPI installation is not enabled"
+            ansible_homebrew_enabled=true
+        elif is_ansible_pypi_disabled; then
+            debug "PyPI installation is disabled"
+            ansible_homebrew_enabled=true
+        fi
+    fi
+}
+
 # Install Ansible on macOS
 install_ansible_on_macos() {
 
+    debug "install Ansible on macOS"
+
+    configure_ansible_on_macos
+
     if is_ansible_installed; then
+        debug "existing Ansible version found, not installing..."
         return 0
     fi
 
     echo "Install Ansible on macOS..."
 
-    # Enable Homebrew installation as the default option if neither Homebrew or
-    # PyPI installation option have been set or if PyPI has been disabled.
-    if [ -z "${ansible_homebrew_enabled}" ]; then
-        if [ -z "${ansible_pypi_enabled}" ]; then
-            ansible_homebrew_enabled=true
-        elif is_ansible_pypi_disabled; then
-            ansible_homebrew_enabled=true
-        fi
-    fi
-
     # Install Ansible from Homebrew
     if is_ansible_homebrew_enabled; then
+        debug "install Ansible from Homebrew"
         if is_true "${is_macos}"; then
             if install_ansible_with_homebrew; then
                 return 0
@@ -929,10 +1019,13 @@ ansible_exec() {
 
     # Get Homebrew Ansible installation prefix
     if is_ansible_homebrew_enabled; then
+        debug "ansible_exec: Ansible Homebrew enabled"
         local prefix
         prefix="$(brew --prefix ansible)"
+        debug "ansible_exec: Ansible prefix: ${prefix}"
         if [ -n "${prefix}" ] && [ -d "${prefix}/bin" ]; then
             ansible_path="${prefix}/bin"
+            debug "ansible_exec: use Ansible from Homebrew"
         fi
     fi
 
@@ -1388,6 +1481,10 @@ while [[ $# -gt 0 ]]; do
             ;;
         --no-install-roles)
             install_roles=0
+            shift
+            ;;
+        --upgrade-ansible)
+            upgrade_ansible=1
             shift
             ;;
         --update-roles)
